//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 03:44:01 PM CST 
//


package com.shenghsiang.mirle.d0401;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INVOICE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SELLERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="POSSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="POSID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SYSTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ALLOWANCENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ALLOWANCEDATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IDENTIFIER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PERSONINCHARGE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TELEPHONENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="FACSIMILENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="EMAILADDRESS" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ROLEREMARK" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ALLOWANCETYPE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="PRODUCTITEM">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ORIGINALINVOICEDATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ORIGINALINVOICENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ORIGINALSEQUENCENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ORIGINALDESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="QUANTITY" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="UNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="UNITPRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                   &lt;element name="TAX" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="ALLOWANCESEQUENCENUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="TAXTYPE" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="TAXAMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="TOTALAMOUNT" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "Allowance")
public class Allowance {

    @XmlElementRefs({
        @XmlElementRef(name = "PRODUCTITEM", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "ALLOWANCENUMBER", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "ADDRESS", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "SELLERID", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "PERSONINCHARGE", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "ALLOWANCETYPE", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "EMAILADDRESS", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "POSID", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "ALLOWANCEDATE", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "SYSTIME", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "TAXAMOUNT", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "POSSN", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "INVOICE_CODE", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "TELEPHONENUMBER", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "TOTALAMOUNT", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "IDENTIFIER", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "ROLEREMARK", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "NAME", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class),
        @XmlElementRef(name = "FACSIMILENUMBER", namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link Allowance.PRODUCTITEM }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link Integer }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ORIGINALINVOICEDATE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ORIGINALINVOICENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ORIGINALSEQUENCENUMBER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ORIGINALDESCRIPTION" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="QUANTITY" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="UNIT" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="UNITPRICE" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="AMOUNT" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *         &lt;element name="TAX" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="ALLOWANCESEQUENCENUMBER" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="TAXTYPE" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "originalinvoicedate",
        "originalinvoicenumber",
        "originalsequencenumber",
        "originaldescription",
        "quantity",
        "unit",
        "unitprice",
        "amount",
        "tax",
        "allowancesequencenumber",
        "taxtype"
    })
    public static class PRODUCTITEM {

        @XmlElement(name = "ORIGINALINVOICEDATE", required = true)
        protected String originalinvoicedate;
        @XmlElement(name = "ORIGINALINVOICENUMBER", required = true)
        protected String originalinvoicenumber;
        @XmlElement(name = "ORIGINALSEQUENCENUMBER", required = true)
        protected int originalsequencenumber;
        @XmlElement(name = "ORIGINALDESCRIPTION", required = true)
        protected String originaldescription;
        @XmlElement(name = "QUANTITY")
        protected float quantity;
        @XmlElement(name = "UNIT", required = true)
        protected String unit;
        @XmlElement(name = "UNITPRICE")
        protected float unitprice;
        @XmlElement(name = "AMOUNT")
        protected float amount;
        @XmlElement(name = "TAX")
        protected int tax;
        @XmlElement(name = "ALLOWANCESEQUENCENUMBER")
        protected int allowancesequencenumber;
        @XmlElement(name = "TAXTYPE")
        protected int taxtype;

        /**
         * Gets the value of the originalinvoicedate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getORIGINALINVOICEDATE() {
            return originalinvoicedate;
        }

        /**
         * Sets the value of the originalinvoicedate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setORIGINALINVOICEDATE(String value) {
            this.originalinvoicedate = value;
        }

        /**
         * Gets the value of the originalinvoicenumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getORIGINALINVOICENUMBER() {
            return originalinvoicenumber;
        }

        /**
         * Sets the value of the originalinvoicenumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setORIGINALINVOICENUMBER(String value) {
            this.originalinvoicenumber = value;
        }

        /**
         * Gets the value of the originalsequencenumber property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public int getORIGINALSEQUENCENUMBER() {
            return originalsequencenumber;
        }

        /**
         * Sets the value of the originalsequencenumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link int }
         *     
         */
        public void setORIGINALSEQUENCENUMBER(int value) {
            this.originalsequencenumber = value;
        }

        /**
         * Gets the value of the originaldescription property.
         * 
         * @return
         *     possible object is
         *     {@link int }
         *     
         */
        public String getORIGINALDESCRIPTION() {
            return originaldescription;
        }

        /**
         * Sets the value of the originaldescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setORIGINALDESCRIPTION(String value) {
            this.originaldescription = value;
        }

        /**
         * Gets the value of the quantity property.
         * 
         */
        public float getQUANTITY() {
            return quantity;
        }

        /**
         * Sets the value of the quantity property.
         * 
         */
        public void setQUANTITY(float value) {
            this.quantity = value;
        }

        /**
         * Gets the value of the unit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUNIT() {
            return unit;
        }

        /**
         * Sets the value of the unit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUNIT(String value) {
            this.unit = value;
        }

        /**
         * Gets the value of the unitprice property.
         * 
         */
        public float getUNITPRICE() {
            return unitprice;
        }

        /**
         * Sets the value of the unitprice property.
         * 
         */
        public void setUNITPRICE(float value) {
            this.unitprice = value;
        }

        /**
         * Gets the value of the amount property.
         * 
         */
        public float getAMOUNT() {
            return amount;
        }

        /**
         * Sets the value of the amount property.
         * 
         */
        public void setAMOUNT(float value) {
            this.amount = value;
        }

        /**
         * Gets the value of the tax property.
         * 
         */
        public int getTAX() {
            return tax;
        }

        /**
         * Sets the value of the tax property.
         * 
         */
        public void setTAX(int value) {
            this.tax = value;
        }

        /**
         * Gets the value of the allowancesequencenumber property.
         * 
         */
        public int getALLOWANCESEQUENCENUMBER() {
            return allowancesequencenumber;
        }

        /**
         * Sets the value of the allowancesequencenumber property.
         * 
         */
        public void setALLOWANCESEQUENCENUMBER(int value) {
            this.allowancesequencenumber = value;
        }

        /**
         * Gets the value of the taxtype property.
         * 
         */
        public int getTAXTYPE() {
            return taxtype;
        }

        /**
         * Sets the value of the taxtype property.
         * 
         */
        public void setTAXTYPE(int value) {
            this.taxtype = value;
        }

    }

}
