//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 03:44:01 PM CST 
//


package com.shenghsiang.mirle.d0401;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mirle.model.d0401 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AllowanceNAME_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "NAME");
    private final static QName _AllowanceTAXAMOUNT_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "TAXAMOUNT");
    private final static QName _AllowanceROLEREMARK_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "ROLEREMARK");
    private final static QName _AllowanceSELLERID_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "SELLERID");
    private final static QName _AllowanceALLOWANCENUMBER_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "ALLOWANCENUMBER");
    private final static QName _AllowanceADDRESS_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "ADDRESS");
    private final static QName _AllowanceALLOWANCETYPE_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "ALLOWANCETYPE");
    private final static QName _AllowancePOSSN_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "POSSN");
    private final static QName _AllowanceIDENTIFIER_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "IDENTIFIER");
    private final static QName _AllowancePERSONINCHARGE_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "PERSONINCHARGE");
    private final static QName _AllowanceSYSTIME_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "SYSTIME");
    private final static QName _AllowanceFACSIMILENUMBER_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "FACSIMILENUMBER");
    private final static QName _AllowancePOSID_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "POSID");
    private final static QName _AllowanceINVOICECODE_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "INVOICE_CODE");
    private final static QName _AllowanceALLOWANCEDATE_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "ALLOWANCEDATE");
    private final static QName _AllowanceTOTALAMOUNT_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "TOTALAMOUNT");
    private final static QName _AllowancePRODUCTITEM_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "PRODUCTITEM");
    private final static QName _AllowanceEMAILADDRESS_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "EMAILADDRESS");
    private final static QName _AllowanceTELEPHONENUMBER_QNAME = new QName("urn:GEINV:eInvoiceMessage:D0401:3.0", "TELEPHONENUMBER");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mirle.model.d0401
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Allowance }
     * 
     */
    public Allowance createAllowance() {
        return new Allowance();
    }

    /**
     * Create an instance of {@link Allowance.PRODUCTITEM }
     * 
     */
    public Allowance.PRODUCTITEM createAllowancePRODUCTITEM() {
        return new Allowance.PRODUCTITEM();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "NAME", scope = Allowance.class)
    public JAXBElement<String> createAllowanceNAME(String value) {
        return new JAXBElement<String>(_AllowanceNAME_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "TAXAMOUNT", scope = Allowance.class)
    public JAXBElement<Integer> createAllowanceTAXAMOUNT(Integer value) {
        return new JAXBElement<Integer>(_AllowanceTAXAMOUNT_QNAME, Integer.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "ROLEREMARK", scope = Allowance.class)
    public JAXBElement<String> createAllowanceROLEREMARK(String value) {
        return new JAXBElement<String>(_AllowanceROLEREMARK_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "SELLERID", scope = Allowance.class)
    public JAXBElement<String> createAllowanceSELLERID(String value) {
        return new JAXBElement<String>(_AllowanceSELLERID_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "ALLOWANCENUMBER", scope = Allowance.class)
    public JAXBElement<String> createAllowanceALLOWANCENUMBER(String value) {
        return new JAXBElement<String>(_AllowanceALLOWANCENUMBER_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "ADDRESS", scope = Allowance.class)
    public JAXBElement<String> createAllowanceADDRESS(String value) {
        return new JAXBElement<String>(_AllowanceADDRESS_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "ALLOWANCETYPE", scope = Allowance.class)
    public JAXBElement<Integer> createAllowanceALLOWANCETYPE(Integer value) {
        return new JAXBElement<Integer>(_AllowanceALLOWANCETYPE_QNAME, Integer.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "POSSN", scope = Allowance.class)
    public JAXBElement<String> createAllowancePOSSN(String value) {
        return new JAXBElement<String>(_AllowancePOSSN_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "IDENTIFIER", scope = Allowance.class)
    public JAXBElement<String> createAllowanceIDENTIFIER(String value) {
        return new JAXBElement<String>(_AllowanceIDENTIFIER_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "PERSONINCHARGE", scope = Allowance.class)
    public JAXBElement<String> createAllowancePERSONINCHARGE(String value) {
        return new JAXBElement<String>(_AllowancePERSONINCHARGE_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "SYSTIME", scope = Allowance.class)
    public JAXBElement<String> createAllowanceSYSTIME(String value) {
        return new JAXBElement<String>(_AllowanceSYSTIME_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "FACSIMILENUMBER", scope = Allowance.class)
    public JAXBElement<String> createAllowanceFACSIMILENUMBER(String value) {
        return new JAXBElement<String>(_AllowanceFACSIMILENUMBER_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "POSID", scope = Allowance.class)
    public JAXBElement<String> createAllowancePOSID(String value) {
        return new JAXBElement<String>(_AllowancePOSID_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "INVOICE_CODE", scope = Allowance.class)
    public JAXBElement<String> createAllowanceINVOICECODE(String value) {
        return new JAXBElement<String>(_AllowanceINVOICECODE_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "ALLOWANCEDATE", scope = Allowance.class)
    public JAXBElement<String> createAllowanceALLOWANCEDATE(String value) {
        return new JAXBElement<String>(_AllowanceALLOWANCEDATE_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "TOTALAMOUNT", scope = Allowance.class)
    public JAXBElement<Integer> createAllowanceTOTALAMOUNT(Integer value) {
        return new JAXBElement<Integer>(_AllowanceTOTALAMOUNT_QNAME, Integer.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Allowance.PRODUCTITEM }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "PRODUCTITEM", scope = Allowance.class)
    public JAXBElement<Allowance.PRODUCTITEM> createAllowancePRODUCTITEM(Allowance.PRODUCTITEM value) {
        return new JAXBElement<Allowance.PRODUCTITEM>(_AllowancePRODUCTITEM_QNAME, Allowance.PRODUCTITEM.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "EMAILADDRESS", scope = Allowance.class)
    public JAXBElement<String> createAllowanceEMAILADDRESS(String value) {
        return new JAXBElement<String>(_AllowanceEMAILADDRESS_QNAME, String.class, Allowance.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", name = "TELEPHONENUMBER", scope = Allowance.class)
    public JAXBElement<String> createAllowanceTELEPHONENUMBER(String value) {
        return new JAXBElement<String>(_AllowanceTELEPHONENUMBER_QNAME, String.class, Allowance.class, value);
    }

}
