//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.15 at 03:44:01 PM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:GEINV:eInvoiceMessage:D0401:3.0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED, xmlns = {
		@javax.xml.bind.annotation.XmlNs(prefix = "", namespaceURI = "urn:GEINV:eInvoiceMessage:D0401:3.0"),
		@javax.xml.bind.annotation.XmlNs(prefix = "xsi", namespaceURI = "http://www.w3.org/2001/XMLSchema-instance") })
package com.shenghsiang.mirle.d0401;

