//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.28 at 01:48:12 PM CST 
//


package com.shenghsiang.mirle.c03;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="INVOICE_CODE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SELLERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="POSID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="POSSN" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="SYSTIME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="INVOICEDATA">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SELLERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TYPENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TAXMONTH" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="INVOICEHEADER" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="INVOICESTART" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="INVOICEEND" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "invoicecode",
    "sellerid",
    "posid",
    "possn",
    "systime",
    "invoicedata"
})
@XmlRootElement(name = "INDEX")
public class INDEX {

    @XmlElement(name = "INVOICE_CODE", required = true)
    protected String invoicecode;
    @XmlElement(name = "SELLERID", required = true)
    protected String sellerid;
    @XmlElement(name = "POSID")
    protected String posid;
    @XmlElement(name = "POSSN", required = true)
    protected String possn;
    @XmlElement(name = "SYSTIME", required = true)
    protected String systime;
    @XmlElement(name = "INVOICEDATA", required = true)
    protected INDEX.INVOICEDATA invoicedata;

    /**
     * Gets the value of the invoicecode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINVOICECODE() {
        return invoicecode;
    }

    /**
     * Sets the value of the invoicecode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINVOICECODE(String value) {
        this.invoicecode = value;
    }

    /**
     * Gets the value of the sellerid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSELLERID() {
        return sellerid;
    }

    /**
     * Sets the value of the sellerid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSELLERID(String value) {
        this.sellerid = value;
    }

    /**
     * Gets the value of the posid property.
     * 
     */
    public String getPOSID() {
        return posid;
    }

    /**
     * Sets the value of the posid property.
     * 
     */
    public void setPOSID(String value) {
        this.posid = value;
    }

    /**
     * Gets the value of the possn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOSSN() {
        return possn;
    }

    /**
     * Sets the value of the possn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOSSN(String value) {
        this.possn = value;
    }

    /**
     * Gets the value of the systime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSYSTIME() {
        return systime;
    }

    /**
     * Sets the value of the systime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSYSTIME(String value) {
        this.systime = value;
    }

    /**
     * Gets the value of the invoicedata property.
     * 
     * @return
     *     possible object is
     *     {@link INDEX.INVOICEDATA }
     *     
     */
    public INDEX.INVOICEDATA getINVOICEDATA() {
        return invoicedata;
    }

    /**
     * Sets the value of the invoicedata property.
     * 
     * @param value
     *     allowed object is
     *     {@link INDEX.INVOICEDATA }
     *     
     */
    public void setINVOICEDATA(INDEX.INVOICEDATA value) {
        this.invoicedata = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SELLERID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TYPE" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TYPENAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TAXMONTH" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="INVOICEHEADER" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="INVOICESTART" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="INVOICEEND" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "sellerid",
        "type",
        "typename",
        "taxmonth",
        "invoiceheader",
        "invoicestart",
        "invoiceend"
    })
    public static class INVOICEDATA {

        @XmlElement(name = "SELLERID", required = true)
        protected String sellerid;
        @XmlElement(name = "TYPE", required = true)
        protected String type;
        @XmlElement(name = "TYPENAME", required = true)
        protected String typename;
        @XmlElement(name = "TAXMONTH", required = true)
        protected String taxmonth;
        @XmlElement(name = "INVOICEHEADER", required = true)
        protected String invoiceheader;
        @XmlElement(name = "INVOICESTART", required = true)
        protected String invoicestart;
        @XmlElement(name = "INVOICEEND", required = true)
        protected String invoiceend;

        /**
         * Gets the value of the sellerid property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSELLERID() {
            return sellerid;
        }

        /**
         * Sets the value of the sellerid property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSELLERID(String value) {
            this.sellerid = value;
        }

        /**
         * Gets the value of the type property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTYPE() {
            return type;
        }

        /**
         * Sets the value of the type property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTYPE(String value) {
            this.type = value;
        }

        /**
         * Gets the value of the typename property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTYPENAME() {
            return typename;
        }

        /**
         * Sets the value of the typename property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTYPENAME(String value) {
            this.typename = value;
        }

        /**
         * Gets the value of the taxmonth property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTAXMONTH() {
            return taxmonth;
        }

        /**
         * Sets the value of the taxmonth property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTAXMONTH(String value) {
            this.taxmonth = value;
        }

        /**
         * Gets the value of the invoiceheader property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINVOICEHEADER() {
            return invoiceheader;
        }

        /**
         * Sets the value of the invoiceheader property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINVOICEHEADER(String value) {
            this.invoiceheader = value;
        }

        /**
         * Gets the value of the invoicestart property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINVOICESTART() {
            return invoicestart;
        }

        /**
         * Sets the value of the invoicestart property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINVOICESTART(String value) {
            this.invoicestart = value;
        }

        /**
         * Gets the value of the invoiceend property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getINVOICEEND() {
            return invoiceend;
        }

        /**
         * Sets the value of the invoiceend property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setINVOICEEND(String value) {
            this.invoiceend = value;
        }

    }

}
