//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.24 at 04:48:47 PM CST 
//


package com.shenghsiang.mirle.c0401;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="A1" type="{}MessageTypeEnum"/>
 *         &lt;element name="A2" type="{}InvoiceNumberType"/>
 *         &lt;element name="A3" type="{}DateType"/>
 *         &lt;element name="A4" type="{}TimeType"/>
 *         &lt;element name="A5" type="{}BAN"/>
 *         &lt;element name="A6">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="A7" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="A8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A10" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A11" type="{}emailAddress" minOccurs="0"/>
 *         &lt;element name="A12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A13" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A14" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A15" type="{}BuyerRemarkEnum" minOccurs="0"/>
 *         &lt;element name="A16" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A17" type="{}CustomsClearanceMarkEnum" minOccurs="0"/>
 *         &lt;element name="A18" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="A19" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="A20" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="A21" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="A22" type="{}InvoiceTypeEnum"/>
 *         &lt;element name="A23" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A24" type="{}DonateMarkEnum"/>
 *         &lt;element name="A25" type="{}CarrierTypeEnum" minOccurs="0"/>
 *         &lt;element name="A26" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A27" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="A28">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Y"/>
 *               &lt;enumeration value="N"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="A29" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="A30" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="B" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="B1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="B2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="B3">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="20"/>
 *                         &lt;fractionDigits value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="B4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="B5">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="20"/>
 *                         &lt;fractionDigits value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="B6">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;totalDigits value="20"/>
 *                         &lt;fractionDigits value="6"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="B7" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="B8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="B9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="B10" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="B11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="B12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="C1" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="C2" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="C3" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="C4" type="{}TaxTypeEnum"/>
 *         &lt;element name="C5" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="C6" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="C7" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="C8" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="C9" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="C10" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="C11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="D1" type="{}InvoiceNumberType"/>
 *         &lt;element name="D2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="D3" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="D4" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="D5" type="{}InvoiceNumberType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "a1",
    "a2",
    "a3",
    "a4",
    "a5",
    "a6",
    "a7",
    "a8",
    "a9",
    "a10",
    "a11",
    "a12",
    "a13",
    "a14",
    "a15",
    "a16",
    "a17",
    "a18",
    "a19",
    "a20",
    "a21",
    "a22",
    "a23",
    "a24",
    "a25",
    "a26",
    "a27",
    "a28",
    "a29",
    "a30",
    "b",
    "c1",
    "c2",
    "c3",
    "c4",
    "c5",
    "c6",
    "c7",
    "c8",
    "c9",
    "c10",
    "c11",
    "d1",
    "d2",
    "d3",
    "d4",
    "d5"
})
@XmlRootElement(name = "Invoice")
public class Invoice {

    @XmlElement(name = "A1", required = true)
    protected MessageTypeEnum a1;
    @XmlElement(name = "A2", required = true)
    protected String a2;
    @XmlElement(name = "A3", required = true)
    protected String a3;
    @XmlElement(name = "A4", required = true)
    // protected XMLGregorianCalendar a4;
    protected String a4;
    @XmlElement(name = "A5", required = true)
    protected String a5;
    @XmlElement(name = "A6", required = true)
    protected String a6;
    @XmlElement(name = "A7")
    protected String a7;
    @XmlElement(name = "A8")
    protected String a8;
    @XmlElement(name = "A9")
    protected String a9;
    @XmlElement(name = "A10")
    protected String a10;
    @XmlElement(name = "A11")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String a11;
    @XmlElement(name = "A12")
    protected String a12;
    @XmlElement(name = "A13")
    protected String a13;
    @XmlElement(name = "A14")
    protected String a14;
    @XmlElement(name = "A15")
    protected String a15;
    @XmlElement(name = "A16")
    protected String a16;
    @XmlElement(name = "A17")
    protected String a17;
    @XmlElement(name = "A18", required = true)
    protected String a18;
    @XmlElement(name = "A19", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar a19;
    @XmlElement(name = "A20", required = true)
    protected String a20;
    @XmlElement(name = "A21", required = true)
    protected String a21;
    @XmlElement(name = "A22", required = true)
    protected String a22;
    @XmlElement(name = "A23")
    protected String a23;
    @XmlElement(name = "A24", required = true, defaultValue = "0")
    protected String a24;
    @XmlElement(name = "A25")
    protected String a25;
    @XmlElement(name = "A26")
    protected String a26;
    @XmlElement(name = "A27")
    protected String a27;
    @XmlElement(name = "A28", required = true, defaultValue = "Y")
    protected String a28;
    @XmlElement(name = "A29")
    protected Integer a29;
    @XmlElement(name = "A30")
    protected int a30;
    @XmlElement(name = "B", required = true)
    protected List<Invoice.B> b;
    @XmlElement(name = "C1")
    protected int c1;
    @XmlElement(name = "C2")
    protected int c2;
    @XmlElement(name = "C3")
    protected int c3;
    @XmlElement(name = "C4", required = true)
    protected String c4;
    @XmlElement(name = "C5")
    protected double c5;
    @XmlElement(name = "C6")
    protected int c6;
    @XmlElement(name = "C7")
    protected int c7;
    @XmlElement(name = "C8")
    protected Integer c8;
    @XmlElement(name = "C9")
    protected Integer c9;
    @XmlElement(name = "C10")
    protected Integer c10;
    @XmlElement(name = "C11")
    protected String c11;
    @XmlElement(name = "D1", required = true)
    protected String d1;
    @XmlElement(name = "D2", required = true)
    protected String d2;
    @XmlElement(name = "D3")
    protected int d3;
    @XmlElement(name = "D4", required = true)
    /*
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar d4;
    */
    protected String d4;
    @XmlElement(name = "D5", required = true)
    protected String d5;

    /**
     * Gets the value of the a1 property.
     * 
     * @return
     *     possible object is
     *     {@link MessageTypeEnum }
     *     
     */
    public MessageTypeEnum getA1() {
        return a1;
    }

    /**
     * Sets the value of the a1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MessageTypeEnum }
     *     
     */
    public void setA1(MessageTypeEnum value) {
        this.a1 = value;
    }

    /**
     * Gets the value of the a2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA2() {
        return a2;
    }

    /**
     * Sets the value of the a2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA2(String value) {
        this.a2 = value;
    }

    /**
     * Gets the value of the a3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA3() {
        return a3;
    }

    /**
     * Sets the value of the a3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA3(String value) {
        this.a3 = value;
    }

    /**
     * Gets the value of the a4 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    /*
    public XMLGregorianCalendar getA4() {
        return a4;
    }
    */
    public String getA4() {
    	return a4;
    }
    /**
     * Sets the value of the a4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    /*
    public void setA4(XMLGregorianCalendar value) {
        this.a4 = value;
    }
    */
    public void setA4(String value) {
    	this.a4 = value;
    }
    /**
     * Gets the value of the a5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA5() {
        return a5;
    }

    /**
     * Sets the value of the a5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA5(String value) {
        this.a5 = value;
    }

    /**
     * Gets the value of the a6 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA6() {
        return a6;
    }

    /**
     * Sets the value of the a6 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA6(String value) {
        this.a6 = value;
    }

    /**
     * Gets the value of the a7 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA7() {
        return a7;
    }

    /**
     * Sets the value of the a7 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA7(String value) {
        this.a7 = value;
    }

    /**
     * Gets the value of the a8 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA8() {
        return a8;
    }

    /**
     * Sets the value of the a8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA8(String value) {
        this.a8 = value;
    }

    /**
     * Gets the value of the a9 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA9() {
        return a9;
    }

    /**
     * Sets the value of the a9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA9(String value) {
        this.a9 = value;
    }

    /**
     * Gets the value of the a10 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA10() {
        return a10;
    }

    /**
     * Sets the value of the a10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA10(String value) {
        this.a10 = value;
    }

    /**
     * Gets the value of the a11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA11() {
        return a11;
    }

    /**
     * Sets the value of the a11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA11(String value) {
        this.a11 = value;
    }

    /**
     * Gets the value of the a12 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA12() {
        return a12;
    }

    /**
     * Sets the value of the a12 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA12(String value) {
        this.a12 = value;
    }

    /**
     * Gets the value of the a13 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA13() {
        return a13;
    }

    /**
     * Sets the value of the a13 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA13(String value) {
        this.a13 = value;
    }

    /**
     * Gets the value of the a14 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA14() {
        return a14;
    }

    /**
     * Sets the value of the a14 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA14(String value) {
        this.a14 = value;
    }

    /**
     * Gets the value of the a15 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA15() {
        return a15;
    }

    /**
     * Sets the value of the a15 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA15(String value) {
        this.a15 = value;
    }

    /**
     * Gets the value of the a16 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA16() {
        return a16;
    }

    /**
     * Sets the value of the a16 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA16(String value) {
        this.a16 = value;
    }

    /**
     * Gets the value of the a17 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA17() {
        return a17;
    }

    /**
     * Sets the value of the a17 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA17(String value) {
        this.a17 = value;
    }

    /**
     * Gets the value of the a18 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA18() {
        return a18;
    }

    /**
     * Sets the value of the a18 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA18(String value) {
        this.a18 = value;
    }

    /**
     * Gets the value of the a19 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getA19() {
        return a19;
    }

    /**
     * Sets the value of the a19 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setA19(XMLGregorianCalendar value) {
        this.a19 = value;
    }

    /**
     * Gets the value of the a20 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA20() {
        return a20;
    }

    /**
     * Sets the value of the a20 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA20(String value) {
        this.a20 = value;
    }

    /**
     * Gets the value of the a21 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA21() {
        return a21;
    }

    /**
     * Sets the value of the a21 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA21(String value) {
        this.a21 = value;
    }

    /**
     * Gets the value of the a22 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA22() {
        return a22;
    }

    /**
     * Sets the value of the a22 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA22(String value) {
        this.a22 = value;
    }

    /**
     * Gets the value of the a23 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA23() {
        return a23;
    }

    /**
     * Sets the value of the a23 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA23(String value) {
        this.a23 = value;
    }

    /**
     * Gets the value of the a24 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA24() {
        return a24;
    }

    /**
     * Sets the value of the a24 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA24(String value) {
        this.a24 = value;
    }

    /**
     * Gets the value of the a25 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA25() {
        return a25;
    }

    /**
     * Sets the value of the a25 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA25(String value) {
        this.a25 = value;
    }

    /**
     * Gets the value of the a26 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA26() {
        return a26;
    }

    /**
     * Sets the value of the a26 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA26(String value) {
        this.a26 = value;
    }

    /**
     * Gets the value of the a27 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA27() {
        return a27;
    }

    /**
     * Sets the value of the a27 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA27(String value) {
        this.a27 = value;
    }

    /**
     * Gets the value of the a28 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getA28() {
        return a28;
    }

    /**
     * Sets the value of the a28 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setA28(String value) {
        this.a28 = value;
    }

    /**
     * Gets the value of the a29 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getA29() {
        return a29;
    }

    /**
     * Sets the value of the a29 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setA29(Integer value) {
        this.a29 = value;
    }

    /**
     * Gets the value of the a30 property.
     * 
     */
    public int getA30() {
        return a30;
    }

    /**
     * Sets the value of the a30 property.
     * 
     */
    public void setA30(int value) {
        this.a30 = value;
    }

    /**
     * Gets the value of the b property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the b property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getB().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Invoice.B }
     * 
     * 
     */
    public List<Invoice.B> getB() {
        if (b == null) {
            b = new ArrayList<Invoice.B>();
        }
        return this.b;
    }

    /**
     * Gets the value of the c1 property.
     * 
     */
    public int getC1() {
        return c1;
    }

    /**
     * Sets the value of the c1 property.
     * 
     */
    public void setC1(int value) {
        this.c1 = value;
    }

    /**
     * Gets the value of the c2 property.
     * 
     */
    public int getC2() {
        return c2;
    }

    /**
     * Sets the value of the c2 property.
     * 
     */
    public void setC2(int value) {
        this.c2 = value;
    }

    /**
     * Gets the value of the c3 property.
     * 
     */
    public int getC3() {
        return c3;
    }

    /**
     * Sets the value of the c3 property.
     * 
     */
    public void setC3(int value) {
        this.c3 = value;
    }

    /**
     * Gets the value of the c4 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC4() {
        return c4;
    }

    /**
     * Sets the value of the c4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC4(String value) {
        this.c4 = value;
    }

    /**
     * Gets the value of the c5 property.
     * 
     */
    public double getC5() {
        return c5;
    }

    /**
     * Sets the value of the c5 property.
     * 
     */
    public void setC5(double value) {
        this.c5 = value;
    }

    /**
     * Gets the value of the c6 property.
     * 
     */
    public int getC6() {
        return c6;
    }

    /**
     * Sets the value of the c6 property.
     * 
     */
    public void setC6(int value) {
        this.c6 = value;
    }

    /**
     * Gets the value of the c7 property.
     * 
     */
    public int getC7() {
        return c7;
    }

    /**
     * Sets the value of the c7 property.
     * 
     */
    public void setC7(int value) {
        this.c7 = value;
    }

    /**
     * Gets the value of the c8 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getC8() {
        return c8;
    }

    /**
     * Sets the value of the c8 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setC8(Integer value) {
        this.c8 = value;
    }

    /**
     * Gets the value of the c9 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getC9() {
        return c9;
    }

    /**
     * Sets the value of the c9 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setC9(Integer value) {
        this.c9 = value;
    }

    /**
     * Gets the value of the c10 property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getC10() {
        return c10;
    }

    /**
     * Sets the value of the c10 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setC10(Integer value) {
        this.c10 = value;
    }

    /**
     * Gets the value of the c11 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getC11() {
        return c11;
    }

    /**
     * Sets the value of the c11 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setC11(String value) {
        this.c11 = value;
    }

    /**
     * Gets the value of the d1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getD1() {
        return d1;
    }

    /**
     * Sets the value of the d1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setD1(String value) {
        this.d1 = value;
    }

    /**
     * Gets the value of the d2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getD2() {
        return d2;
    }

    /**
     * Sets the value of the d2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setD2(String value) {
        this.d2 = value;
    }

    /**
     * Gets the value of the d3 property.
     * 
     */
    public int getD3() {
        return d3;
    }

    /**
     * Sets the value of the d3 property.
     * 
     */
    public void setD3(int value) {
        this.d3 = value;
    }

    /**
     * Gets the value of the d4 property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    /*
    public XMLGregorianCalendar getD4() {
        return d4;
    }
    */
    public String getD4() {
    	return d4;
    }

    /**
     * Sets the value of the d4 property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    /*
    public void setD4(XMLGregorianCalendar value) {
        this.d4 = value;
    }
    */
    public void setD4(String value) {
    	this.d4 = value;
    }

    /**
     * Gets the value of the d5 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getD5() {
        return d5;
    }

    /**
     * Sets the value of the d5 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setD5(String value) {
        this.d5 = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="B1" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="B2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="B3">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="20"/>
     *               &lt;fractionDigits value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="B4" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="B5">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="20"/>
     *               &lt;fractionDigits value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="B6">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;totalDigits value="20"/>
     *               &lt;fractionDigits value="6"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="B7" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="B8" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="B9" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="B10" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="B11" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="B12" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "b1",
        "b2",
        "b3",
        "b4",
        "b5",
        "b6",
        "b7",
        "b8",
        "b9",
        "b10",
        "b11",
        "b12"
    })
    public static class B {

        @XmlElement(name = "B1")
        protected int b1;
        @XmlElement(name = "B2", required = true)
        protected String b2;
        @XmlElement(name = "B3", required = true)
        protected BigDecimal b3;
        @XmlElement(name = "B4")
        protected String b4;
        @XmlElement(name = "B5", required = true)
        protected BigDecimal b5;
        @XmlElement(name = "B6", required = true)
        protected BigDecimal b6;
        @XmlElement(name = "B7")
        protected int b7;
        @XmlElement(name = "B8")
        protected String b8;
        @XmlElement(name = "B9")
        protected String b9;
        @XmlElement(name = "B10")
        protected Integer b10;
        @XmlElement(name = "B11")
        protected String b11;
        @XmlElement(name = "B12")
        protected String b12;

        /**
         * Gets the value of the b1 property.
         * 
         */
        public int getB1() {
            return b1;
        }

        /**
         * Sets the value of the b1 property.
         * 
         */
        public void setB1(int value) {
            this.b1 = value;
        }

        /**
         * Gets the value of the b2 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getB2() {
            return b2;
        }

        /**
         * Sets the value of the b2 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setB2(String value) {
            this.b2 = value;
        }

        /**
         * Gets the value of the b3 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getB3() {
            return b3;
        }

        /**
         * Sets the value of the b3 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setB3(BigDecimal value) {
            this.b3 = value;
        }

        /**
         * Gets the value of the b4 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getB4() {
            return b4;
        }

        /**
         * Sets the value of the b4 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setB4(String value) {
            this.b4 = value;
        }

        /**
         * Gets the value of the b5 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getB5() {
            return b5;
        }

        /**
         * Sets the value of the b5 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setB5(BigDecimal value) {
            this.b5 = value;
        }

        /**
         * Gets the value of the b6 property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getB6() {
            return b6;
        }

        /**
         * Sets the value of the b6 property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setB6(BigDecimal value) {
            this.b6 = value;
        }

        /**
         * Gets the value of the b7 property.
         * 
         */
        public int getB7() {
            return b7;
        }

        /**
         * Sets the value of the b7 property.
         * 
         */
        public void setB7(int value) {
            this.b7 = value;
        }

        /**
         * Gets the value of the b8 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getB8() {
            return b8;
        }

        /**
         * Sets the value of the b8 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setB8(String value) {
            this.b8 = value;
        }

        /**
         * Gets the value of the b9 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getB9() {
            return b9;
        }

        /**
         * Sets the value of the b9 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setB9(String value) {
            this.b9 = value;
        }

        /**
         * Gets the value of the b10 property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getB10() {
            return b10;
        }

        /**
         * Sets the value of the b10 property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setB10(Integer value) {
            this.b10 = value;
        }

        /**
         * Gets the value of the b11 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getB11() {
            return b11;
        }

        /**
         * Sets the value of the b11 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setB11(String value) {
            this.b11 = value;
        }

        /**
         * Gets the value of the b12 property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getB12() {
            return b12;
        }

        /**
         * Sets the value of the b12 property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setB12(String value) {
            this.b12 = value;
        }

    }

    /*
     * JAXB doesn't add getters to Lists
       use the getter to add the element to the list 
	public void setB(List<Invoice.B> b) {
		this.b = b;
	}
	*/

}
