//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.24 at 04:48:47 PM CST 
//


package com.shenghsiang.mirle.c0401;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.shenghsiang.mirle.c0401 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.shenghsiang.mirle.c0401
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link Invoice.B }
     * 
     */
    public Invoice.B createInvoiceB() {
        return new Invoice.B();
    }

    /**
     * Create an instance of {@link PartyInfoType }
     * 
     */
    public PartyInfoType createPartyInfoType() {
        return new PartyInfoType();
    }

    /**
     * Create an instance of {@link RoutingInfoType }
     * 
     */
    public RoutingInfoType createRoutingInfoType() {
        return new RoutingInfoType();
    }

}
